project_id = "saylo"

[functions.daily-content]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.dispatch-notifications]
verify_jwt = false

[functions.import-curriculum]
verify_jwt = false
